<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PagesMetaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pages_meta')->insert([
            [
                'id' => 1,
                'ref_id' => 1,
                'ref_key' => 'section_one_title',
                'ref_value' => 'Visionary Infrastructure Development, Transforming Tomorrow',
                'created_at' => Carbon::parse('2025-09-08 10:47:55'),
                'updated_at' => Carbon::parse('2025-09-08 10:47:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'ref_id' => 1,
                'ref_key' => 'section_one_button_text',
                'ref_value' => 'See our portfolio',
                'created_at' => Carbon::parse('2025-09-08 10:47:55'),
                'updated_at' => Carbon::parse('2025-09-09 04:08:18'),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'ref_id' => 1,
                'ref_key' => 'section_one_button_link',
                'ref_value' => 'https://www.wacep.com',
                'created_at' => Carbon::parse('2025-09-08 11:47:59'),
                'updated_at' => Carbon::parse('2025-09-08 06:49:05'),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'ref_id' => 1,
                'ref_key' => 'section_two_button_one_text',
                'ref_value' => 'Leading the Future of Innovation',
                'created_at' => Carbon::parse('2025-09-08 12:33:47'),
                'updated_at' => Carbon::parse('2025-09-08 12:33:47'),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'ref_id' => 1,
                'ref_key' => 'section_two_button_one_link',
                'ref_value' => 'https://www.facebook.com',
                'created_at' => Carbon::parse('2025-09-08 12:33:47'),
                'updated_at' => Carbon::parse('2025-09-08 12:33:47'),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'ref_id' => 1,
                'ref_key' => 'section_two_text_one',
                'ref_value' => 'Pioneering the Future: Tanama Capital builds tomorrow’s infrastructure today, where innovation meets impact, and communities thrive.',
                'created_at' => Carbon::parse('2025-09-08 12:46:53'),
                'updated_at' => Carbon::parse('2025-09-08 12:46:53'),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'ref_id' => 1,
                'ref_key' => 'section_two_button_two_text',
                'ref_value' => 'Learn more about us',
                'created_at' => Carbon::parse('2025-09-08 12:52:53'),
                'updated_at' => Carbon::parse('2025-09-08 12:52:53'),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'ref_id' => 1,
                'ref_key' => 'section_two_button_two_link',
                'ref_value' => 'https://www.facebook.com',
                'created_at' => Carbon::parse('2025-09-08 12:55:42'),
                'updated_at' => Carbon::parse('2025-09-08 12:55:42'),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_one',
                'ref_value' => '50+',
                'created_at' => Carbon::parse('2025-09-09 05:06:56'),
                'updated_at' => Carbon::parse('2025-09-09 05:06:56'),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_one_text',
                'ref_value' => 'Projects delivered to date',
                'created_at' => Carbon::parse('2025-09-09 05:06:56'),
                'updated_at' => Carbon::parse('2025-09-09 05:06:56'),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_two',
                'ref_value' => '20+',
                'created_at' => Carbon::parse('2025-09-09 05:09:29'),
                'updated_at' => Carbon::parse('2025-09-09 05:09:29'),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_two_text',
                'ref_value' => 'Backed by a talented team of 20+',
                'created_at' => Carbon::parse('2025-09-09 05:09:29'),
                'updated_at' => Carbon::parse('2025-09-09 05:09:29'),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_three',
                'ref_value' => '5M',
                'created_at' => Carbon::parse('2025-09-09 05:11:43'),
                'updated_at' => Carbon::parse('2025-09-09 05:11:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_three_text',
                'ref_value' => '5 million dollars raised in investment',
                'created_at' => Carbon::parse('2025-09-09 05:11:43'),
                'updated_at' => Carbon::parse('2025-09-09 05:11:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_four',
                'ref_value' => '95%',
                'created_at' => Carbon::parse('2025-09-09 05:14:55'),
                'updated_at' => Carbon::parse('2025-09-09 00:16:42'),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'ref_id' => 1,
                'ref_key' => 'section_two_count_four_text',
                'ref_value' => 'Proud to maintain a 95% client retention',
                'created_at' => Carbon::parse('2025-09-09 05:14:55'),
                'updated_at' => Carbon::parse('2025-09-09 05:14:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'ref_id' => 1,
                'ref_key' => 'section_three_text_one',
                'ref_value' => 'At Tanama Capital, our portfolio is tailored to represent bold visions into operational realities',
                'created_at' => Carbon::parse('2025-09-09 05:28:06'),
                'updated_at' => Carbon::parse('2025-09-09 05:28:06'),
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'ref_id' => 1,
                'ref_key' => 'section_three_button_one_text',
                'ref_value' => 'See all projects',
                'created_at' => Carbon::parse('2025-09-09 05:31:05'),
                'updated_at' => Carbon::parse('2025-09-09 05:31:05'),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'ref_id' => 1,
                'ref_key' => 'section_three_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 05:31:05'),
                'updated_at' => Carbon::parse('2025-09-09 05:31:05'),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'ref_id' => 1,
                'ref_key' => 'section_four_text_one',
                'ref_value' => 'Tanama is a fast growing investor and developer of infrastructure in the middle east and Africa (MEA)',
                'created_at' => Carbon::parse('2025-09-09 05:39:39'),
                'updated_at' => Carbon::parse('2025-09-09 05:39:39'),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'ref_id' => 1,
                'ref_key' => 'section_four_button_one_text',
                'ref_value' => 'learn more about us',
                'created_at' => Carbon::parse('2025-09-09 05:42:49'),
                'updated_at' => Carbon::parse('2025-09-09 05:42:49'),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'ref_id' => 1,
                'ref_key' => 'section_four_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 05:42:49'),
                'updated_at' => Carbon::parse('2025-09-09 05:42:49'),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_text_one',
                'ref_value' => 'At Tanama Capital, sustainability isn’t an afterthought- it’s at the heart of everything we build.',
                'created_at' => Carbon::parse('2025-09-09 05:53:42'),
                'updated_at' => Carbon::parse('2025-09-09 05:53:42'),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_button_one_text',
                'ref_value' => 'learn more',
                'created_at' => Carbon::parse('2025-09-09 06:50:21'),
                'updated_at' => Carbon::parse('2025-09-09 06:50:21'),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 06:51:33'),
                'updated_at' => Carbon::parse('2025-09-09 06:51:33'),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_dropdown_one_title',
                'ref_value' => 'Net Zero goals',
                'created_at' => Carbon::parse('2025-09-09 06:53:55'),
                'updated_at' => Carbon::parse('2025-09-09 06:53:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_dropdown_one_desc',
                'ref_value' => 'We are actively aligning our operations and project frameworks with global net-zero targets. Through energy-efficient design, renewable integration, and carbon-conscious construction practices',
                'created_at' => Carbon::parse('2025-09-09 06:53:55'),
                'updated_at' => Carbon::parse('2025-09-09 06:53:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_dropdown_two_title',
                'ref_value' => 'Climate resilience',
                'created_at' => Carbon::parse('2025-09-09 06:59:15'),
                'updated_at' => Carbon::parse('2025-09-09 06:59:15'),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_dropdown_two_desc',
                'ref_value' => 'We are actively aligning our operations and project frameworks with global net-zero targets. Through energy-efficient design, renewable integration, and carbon-conscious construction practices',
                'created_at' => Carbon::parse('2025-09-09 06:59:15'),
                'updated_at' => Carbon::parse('2025-09-09 06:59:15'),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_dropdown_three_title',
                'ref_value' => 'Innovation for Sustainability',
                'created_at' => Carbon::parse('2025-09-09 07:16:12'),
                'updated_at' => Carbon::parse('2025-09-09 07:16:12'),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'ref_id' => 1,
                'ref_key' => 'section_fifth_dropdown_three_desc',
                'ref_value' => 'We are actively aligning our operations and project frameworks with global net-zero targets. Through energy-efficient design, renewable integration, and carbon-conscious construction practices',
                'created_at' => Carbon::parse('2025-09-09 07:16:12'),
                'updated_at' => Carbon::parse('2025-09-09 07:16:12'),
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'ref_id' => 1,
                'ref_key' => 'section_sixth_text_one',
                'ref_value' => 'Your Guide to Emerging Infrastructure Opportunities',
                'created_at' => Carbon::parse('2025-09-09 07:23:16'),
                'updated_at' => Carbon::parse('2025-09-09 07:23:16'),
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'ref_id' => 1,
                'ref_key' => 'section_sixth_button_one_text',
                'ref_value' => 'see all news',
                'created_at' => Carbon::parse('2025-09-09 07:23:16'),
                'updated_at' => Carbon::parse('2025-09-09 07:23:16'),
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'ref_id' => 1,
                'ref_key' => 'section_sixth_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 07:25:30'),
                'updated_at' => Carbon::parse('2025-09-09 07:25:30'),
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'ref_id' => 1,
                'ref_key' => 'section_seventh_text_one',
                'ref_value' => 'Building Together for a Better Future',
                'created_at' => Carbon::parse('2025-09-09 07:26:25'),
                'updated_at' => Carbon::parse('2025-09-09 07:26:25'),
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'ref_id' => 1,
                'ref_key' => 'section_seventh_button_one_text',
                'ref_value' => 'Let’s Partner',
                'created_at' => Carbon::parse('2025-09-09 07:30:34'),
                'updated_at' => Carbon::parse('2025-09-09 07:30:34'),
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'ref_id' => 1,
                'ref_key' => 'section_seventh_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 07:30:34'),
                'updated_at' => Carbon::parse('2025-09-09 07:30:34'),
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'ref_id' => 2,
                'ref_key' => 'section_one_text_one',
                'ref_value' => 'Innovating Infrastructure. Inspiring Progress',
                'created_at' => Carbon::parse('2025-09-09 09:28:42'),
                'updated_at' => Carbon::parse('2025-09-09 09:28:42'),
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'ref_id' => 2,
                'ref_key' => 'section_one_button_one_text',
                'ref_value' => 'get in touch with us',
                'created_at' => Carbon::parse('2025-09-09 09:28:42'),
                'updated_at' => Carbon::parse('2025-09-09 09:28:42'),
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'ref_id' => 2,
                'ref_key' => 'section_one_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 09:31:55'),
                'updated_at' => Carbon::parse('2025-09-09 09:31:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'ref_id' => 2,
                'ref_key' => 'section_two_button_one_text',
                'ref_value' => 'Leading the Future of Innovation',
                'created_at' => Carbon::parse('2025-09-09 09:35:20'),
                'updated_at' => Carbon::parse('2025-09-09 09:35:20'),
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'ref_id' => 2,
                'ref_key' => 'section_two_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 09:35:20'),
                'updated_at' => Carbon::parse('2025-09-09 09:35:20'),
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'ref_id' => 2,
                'ref_key' => 'section_two_text_one',
                'ref_value' => 'Pioneering the Future: Tanama Capital builds tomorrow’s infrastructure today, where innovation meets impact, and communities thrive.',
                'created_at' => Carbon::parse('2025-09-09 09:37:32'),
                'updated_at' => Carbon::parse('2025-09-09 09:37:32'),
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'ref_id' => 2,
                'ref_key' => 'section_three_title',
                'ref_value' => 'MISSION STATEMENT',
                'created_at' => Carbon::parse('2025-09-09 09:45:55'),
                'updated_at' => Carbon::parse('2025-09-09 09:45:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'ref_id' => 2,
                'ref_key' => 'section_three_description',
                'ref_value' => 'To invest in and develop projects that transform landscapes, empower societies, and leave a lasting positive impact.',
                'created_at' => Carbon::parse('2025-09-09 09:45:55'),
                'updated_at' => Carbon::parse('2025-09-09 09:45:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'ref_id' => 2,
                'ref_key' => 'section_three_button_text',
                'ref_value' => 'See our portfolio',
                'created_at' => Carbon::parse('2025-09-09 09:48:20'),
                'updated_at' => Carbon::parse('2025-09-09 09:48:20'),
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'ref_id' => 2,
                'ref_key' => 'section_three_button_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 09:48:20'),
                'updated_at' => Carbon::parse('2025-09-09 09:48:20'),
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'ref_id' => 2,
                'ref_key' => 'section_fourth_heading',
                'ref_value' => '“We’re building infrastructure that shapes a better tomorrow.”',
                'created_at' => Carbon::parse('2025-09-09 10:04:20'),
                'updated_at' => Carbon::parse('2025-09-09 10:04:20'),
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'ref_id' => 2,
                'ref_key' => 'section_fourth_description',
                'ref_value' => 'We believe that true progress comes from building infrastructure that not only serves today’s needs but also shapes a sustainable and prosperous future for generations to come.',
                'created_at' => Carbon::parse('2025-09-09 10:04:20'),
                'updated_at' => Carbon::parse('2025-09-09 10:04:20'),
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'ref_id' => 2,
                'ref_key' => 'section_fourth_text_one',
                'ref_value' => 'name of the chairmAn',
                'created_at' => Carbon::parse('2025-09-09 10:06:43'),
                'updated_at' => Carbon::parse('2025-09-09 10:06:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'ref_id' => 2,
                'ref_key' => 'section_fourth_text_two',
                'ref_value' => 'Chairman',
                'created_at' => Carbon::parse('2025-09-09 10:06:43'),
                'updated_at' => Carbon::parse('2025-09-09 10:06:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'ref_id' => 2,
                'ref_key' => 'section_fifth_heading',
                'ref_value' => 'The Visionary Minds Leading Our Success',
                'created_at' => Carbon::parse('2025-09-09 10:17:27'),
                'updated_at' => Carbon::parse('2025-09-09 10:17:27'),
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'ref_id' => 2,
                'ref_key' => 'section_sixth_heading',
                'ref_value' => 'Comprehensive Infrastructure Solutions',
                'created_at' => Carbon::parse('2025-09-09 10:19:01'),
                'updated_at' => Carbon::parse('2025-09-09 10:19:01'),
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'ref_id' => 2,
                'ref_key' => 'section_sixth_description',
                'ref_value' => 'At Tanama Capital, we turn ambitious ideas into tangible outcomes building projects that serve society today and inspire generations to come.',
                'created_at' => Carbon::parse('2025-09-09 10:19:01'),
                'updated_at' => Carbon::parse('2025-09-09 10:19:01'),
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'ref_id' => 2,
                'ref_key' => 'section_seventh_text_one',
                'ref_value' => 'Your next investment starts with us',
                'created_at' => Carbon::parse('2025-09-09 10:43:58'),
                'updated_at' => Carbon::parse('2025-09-09 10:43:58'),
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'ref_id' => 3,
                'ref_key' => 'section_one_text_one',
                'ref_value' => 'Your guide to emerging opportunities',
                'created_at' => Carbon::parse('2025-09-09 11:08:26'),
                'updated_at' => Carbon::parse('2025-09-09 11:08:26'),
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'ref_id' => 3,
                'ref_key' => 'section_one_button_text',
                'ref_value' => 'Subscribe to newsletter',
                'created_at' => Carbon::parse('2025-09-09 11:08:26'),
                'updated_at' => Carbon::parse('2025-09-09 11:08:26'),
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'ref_id' => 3,
                'ref_key' => 'section_one_button_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-09 11:16:29'),
                'updated_at' => Carbon::parse('2025-09-09 11:16:29'),
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'ref_id' => 3,
                'ref_key' => 'section_two_text',
                'ref_value' => 'Sign Up for Exclusive Updates',
                'created_at' => Carbon::parse('2025-09-09 11:18:30'),
                'updated_at' => Carbon::parse('2025-09-09 11:18:30'),
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'ref_id' => 3,
                'ref_key' => 'section_two_button_text',
                'ref_value' => 'Subscribe now',
                'created_at' => Carbon::parse('2025-09-09 11:19:17'),
                'updated_at' => Carbon::parse('2025-09-09 06:21:24'),
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'ref_id' => 4,
                'ref_key' => 'section_one_heading',
                'ref_value' => 'Innovating Infrastructure. Inspiring Progress',
                'created_at' => Carbon::parse('2025-09-12 04:54:43'),
                'updated_at' => Carbon::parse('2025-09-12 04:54:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 64,
                'ref_id' => 4,
                'ref_key' => 'section_one_button_text',
                'ref_value' => 'get in touch with us',
                'created_at' => Carbon::parse('2025-09-12 04:54:43'),
                'updated_at' => Carbon::parse('2025-09-12 04:54:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 65,
                'ref_id' => 4,
                'ref_key' => 'section_one_button_link',
                'ref_value' => 'https://www.google.com',
                'created_at' => Carbon::parse('2025-09-12 04:56:07'),
                'updated_at' => Carbon::parse('2025-09-12 04:56:07'),
                'deleted_at' => null,
            ],
            [
                'id' => 66,
                'ref_id' => 4,
                'ref_key' => 'section_two_button_text',
                'ref_value' => 'Leading the Future of Innovation',
                'created_at' => Carbon::parse('2025-09-12 04:58:39'),
                'updated_at' => Carbon::parse('2025-09-12 04:58:39'),
                'deleted_at' => null,
            ],
            [
                'id' => 67,
                'ref_id' => 4,
                'ref_key' => 'section_two_heading',
                'ref_value' => 'Pioneering the Future: Tanama Capital builds tomorrow’s infrastructure today, where innovation meets impact, and communities thrive.',
                'created_at' => Carbon::parse('2025-09-12 04:58:39'),
                'updated_at' => Carbon::parse('2025-09-12 04:58:39'),
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'ref_id' => 4,
                'ref_key' => 'section_three_heading',
                'ref_value' => 'Join Tanama Capital’s Team of Visionaries Driving Growth',
                'created_at' => Carbon::parse('2025-09-12 05:06:46'),
                'updated_at' => Carbon::parse('2025-09-12 05:06:46'),
                'deleted_at' => null,
            ],
            [
                'id' => 69,
                'ref_id' => 5,
                'ref_key' => 'section_one_heading',
                'ref_value' => 'Innovating Infrastructure. Inspiring Progress',
                'created_at' => Carbon::parse('2025-09-12 05:18:29'),
                'updated_at' => Carbon::parse('2025-09-12 05:18:29'),
                'deleted_at' => null,
            ],
            [
                'id' => 70,
                'ref_id' => 5,
                'ref_key' => 'section_one_button',
                'ref_value' => 'get in touch with us',
                'created_at' => Carbon::parse('2025-09-12 05:18:29'),
                'updated_at' => Carbon::parse('2025-09-12 05:18:29'),
                'deleted_at' => null,
            ],
            [
                'id' => 71,
                'ref_id' => 5,
                'ref_key' => 'section_one_button_link',
                'ref_value' => 'https://www.google.com',
                'created_at' => Carbon::parse('2025-09-12 05:19:47'),
                'updated_at' => Carbon::parse('2025-09-12 05:19:47'),
                'deleted_at' => null,
            ],
            [
                'id' => 72,
                'ref_id' => 5,
                'ref_key' => 'section_two_heading',
                'ref_value' => 'Let’s Discuss How We Can Work Together',
                'created_at' => Carbon::parse('2025-09-12 05:21:43'),
                'updated_at' => Carbon::parse('2025-09-12 05:21:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 73,
                'ref_id' => 5,
                'ref_key' => 'section_three_lable_one',
                'ref_value' => 'Head office',
                'created_at' => Carbon::parse('2025-09-12 05:26:34'),
                'updated_at' => Carbon::parse('2025-09-12 05:26:34'),
                'deleted_at' => null,
            ],
            [
                'id' => 74,
                'ref_id' => 5,
                'ref_key' => 'section_three_text_one',
                'ref_value' => '22nd Floor, Vision Tower, Business Bay, Dubai, UAE',
                'created_at' => Carbon::parse('2025-09-12 05:26:34'),
                'updated_at' => Carbon::parse('2025-09-12 05:26:34'),
                'deleted_at' => null,
            ],
            [
                'id' => 75,
                'ref_id' => 5,
                'ref_key' => 'section_three_lable_two',
                'ref_value' => 'Email',
                'created_at' => Carbon::parse('2025-09-12 05:29:07'),
                'updated_at' => Carbon::parse('2025-09-12 05:29:07'),
                'deleted_at' => null,
            ],
            [
                'id' => 76,
                'ref_id' => 5,
                'ref_key' => 'section_three_text_two',
                'ref_value' => 'information@tanamacapital.com',
                'created_at' => Carbon::parse('2025-09-12 05:29:07'),
                'updated_at' => Carbon::parse('2025-09-12 05:29:07'),
                'deleted_at' => null,
            ],
            [
                'id' => 77,
                'ref_id' => 5,
                'ref_key' => 'section_three_lable_three',
                'ref_value' => 'Monday - friday',
                'created_at' => Carbon::parse('2025-09-12 05:31:03'),
                'updated_at' => Carbon::parse('2025-09-12 05:31:03'),
                'deleted_at' => null,
            ],
            [
                'id' => 78,
                'ref_id' => 5,
                'ref_key' => 'section_three_text_three',
                'ref_value' => '09:00am - 08:00 pm',
                'created_at' => Carbon::parse('2025-09-12 05:31:03'),
                'updated_at' => Carbon::parse('2025-09-12 05:31:03'),
                'deleted_at' => null,
            ],
            [
                'id' => 79,
                'ref_id' => 5,
                'ref_key' => 'section_three_lable_four',
                'ref_value' => 'PO box',
                'created_at' => Carbon::parse('2025-09-12 05:32:53'),
                'updated_at' => Carbon::parse('2025-09-12 05:32:53'),
                'deleted_at' => null,
            ],
            [
                'id' => 80,
                'ref_id' => 5,
                'ref_key' => 'section_three_text_four',
                'ref_value' => 'XXXXX',
                'created_at' => Carbon::parse('2025-09-12 05:32:53'),
                'updated_at' => Carbon::parse('2025-09-12 05:32:53'),
                'deleted_at' => null,
            ],
            [
                'id' => 81,
                'ref_id' => 5,
                'ref_key' => 'section_three_lable_five',
                'ref_value' => 'Phone',
                'created_at' => Carbon::parse('2025-09-12 05:34:55'),
                'updated_at' => Carbon::parse('2025-09-12 05:34:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 82,
                'ref_id' => 5,
                'ref_key' => 'section_three_text_five',
                'ref_value' => '+971 XXXXXXXX',
                'created_at' => Carbon::parse('2025-09-12 05:34:55'),
                'updated_at' => Carbon::parse('2025-09-12 05:34:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 83,
                'ref_id' => 5,
                'ref_key' => 'section_three_label_six',
                'ref_value' => 'Sat - sun',
                'created_at' => Carbon::parse('2025-09-12 05:37:03'),
                'updated_at' => Carbon::parse('2025-09-12 05:37:03'),
                'deleted_at' => null,
            ],
            [
                'id' => 84,
                'ref_id' => 5,
                'ref_key' => 'section_three_text_six',
                'ref_value' => 'Closed',
                'created_at' => Carbon::parse('2025-09-12 05:37:03'),
                'updated_at' => Carbon::parse('2025-09-12 05:37:03'),
                'deleted_at' => null,
            ],
            [
                'id' => 85,
                'ref_id' => 6,
                'ref_key' => 'section_one_heading',
                'ref_value' => 'We build tomorrow’s infrastructure today',
                'created_at' => Carbon::parse('2025-09-12 09:11:36'),
                'updated_at' => Carbon::parse('2025-09-12 09:11:36'),
                'deleted_at' => null,
            ],
            [
                'id' => 86,
                'ref_id' => 6,
                'ref_key' => 'section_one_button_text',
                'ref_value' => 'Subscribe to newsletter',
                'created_at' => Carbon::parse('2025-09-12 09:11:36'),
                'updated_at' => Carbon::parse('2025-09-12 09:11:36'),
                'deleted_at' => null,
            ],
            [
                'id' => 87,
                'ref_id' => 6,
                'ref_key' => 'section_one_button_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-12 09:12:39'),
                'updated_at' => Carbon::parse('2025-09-12 09:12:39'),
                'deleted_at' => null,
            ],
            [
                'id' => 88,
                'ref_id' => 6,
                'ref_key' => 'section_two_button_one_text',
                'ref_value' => 'sustainability commitments',
                'created_at' => Carbon::parse('2025-09-12 09:25:43'),
                'updated_at' => Carbon::parse('2025-09-12 09:25:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 89,
                'ref_id' => 6,
                'ref_key' => 'section_two_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-12 09:25:43'),
                'updated_at' => Carbon::parse('2025-09-12 09:25:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 92,
                'ref_id' => 6,
                'ref_key' => 'section_two_heading',
                'ref_value' => 'Pioneering the Future: Tanama Capital builds tomorrow’s infrastructure today, where innovation meets impact, and communities thrive.',
                'created_at' => Carbon::parse('2025-09-12 09:28:49'),
                'updated_at' => Carbon::parse('2025-09-12 09:28:49'),
                'deleted_at' => null,
            ],
            [
                'id' => 93,
                'ref_id' => 6,
                'ref_key' => 'section_two_button_two_text',
                'ref_value' => 'See our sustainable projects',
                'created_at' => Carbon::parse('2025-09-12 09:31:05'),
                'updated_at' => Carbon::parse('2025-09-12 09:31:05'),
                'deleted_at' => null,
            ],
            [
                'id' => 94,
                'ref_id' => 6,
                'ref_key' => 'section_two_button_two_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => Carbon::parse('2025-09-12 09:31:05'),
                'updated_at' => Carbon::parse('2025-09-12 09:31:05'),
                'deleted_at' => null,
            ],
        ]);
    }
}
